### PR TITLE
#78-Create-JobCard-Component-Meysam-Arshadi

### LINKED ISSUE #78: Create a new `JobCard` component
Each individual job should be shown inside a new `JobCard` component.

Include these props
- `title`
- `location`
- It should also have an `onClick` prop which is fired when the component is clicked

### PR DESCRIPTION
**Pull request by Meysam-Arshadi**
Fixes #78 

- [x] `JobCard.jsx` created.
- [x]  `JobCardContainer` modified to show JobCards.
- [x]  `{ jobs.map((job)...) }` moved from `JobCardContainer.jsx` to `JobCard.jsx`.
- [ ] We carnally map jobs inside `JobCard.jsx`, and `{ jobs.map((job)...) }` should be replaced once the `Search component` is working.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Comment by Meysam-Arshadi** [comment]
I made `90380be commit` in a wrong branch and reverted it. Please ignore and only review\merge changes in `commit 33c4283` `JobCard component created`

**Comment by OlushoreOdude** [comment]
@Meysam-Arshadi can you clarify? The commits mentioned are all on the same branch, merging the last commit will merge the the previous commits.

**Comment by Meysam-Arshadi** [comment]
Thank @OlushoreOdude.
The first commit is ok and was intended for this branch. You can see it at the top of this PR: [JobCard component created](https://github.com/OlushoreOdude/nyf-job-board/pull/89/commits/33c4283669203392f05cd5577b67ff6836d666fd)
The last commit was mad by mistake: [SelectedJob component created](https://github.com/OlushoreOdude/nyf-job-board/pull/89/commits/90380be66aa79cd04e97c9b070e1b08cad31c80e)
I reverted that commit: @Meysam-Arshadi
[Revert "SelectedJob component created"](https://github.com/OlushoreOdude/nyf-job-board/pull/89/commits/daf06b1da4d9e0967cf97ac11a277242dce57474)
So if you check the PR and merge it, it will only merge the correct commit.

**Comment by OlushoreOdude** [comment]
Thanks @Meysam-Arshadi is see what you mean, good use of git revert. suggestions for clarity
-  `git revert -no-commit` and customise the commit message with a manual commit

i'll check new commit and merge.

**Pull request closed without merging**
